### ISSUE TITLE
WEBSITE! Not found...

### ISSUE THREAD

**Issue by Taki21** [Inactive-to-Reactive/Inactive-to-Reactive.github.io#1]

**Comment by remotevase** [comment]
I know, im still working on the website. Then I will make fix it. I clearly understand the problem, though...

**Comment by remotevase** [comment]
Gonna leave issue open so progress can be easily told

**Comment by remotevase** [comment]
Done

**Comment by Taki21** [comment]
thx

**Comment by Taki21** [comment]
LOL!

**Comment by Taki21** [comment]
whats about21.html?
Like my name? Taki**21** xD

**Comment by remotevase** [comment]
no, because they are indev, I put 21 after each of them because you are the only other person who has helped on the website who has numbers in their name!

**Comment by Taki21** [comment]
aww : ( u no like me name waaah waaah xD

**Comment by remotevase** [comment]
What makes you say that?
