### ISSUE TITLE
Broken Website?

### ISSUE THREAD

**Issue by jasonwynn10** [Inactive-to-Reactive/Inactive-to-Reactive.github.io#2]
It looks like the current website that is set up is broken... If you want, I could make a new one that looks better and can respond to the user.

**Comment by remotevase** [comment]
Yes please. Currently, I used a template, but the parts that are broken redirect to pagename21.html because pagename.html is still the template not edited!

**Comment by jasonwynn10** [comment]
I'll get right on it then...

**Comment by remotevase** [comment]
You don't have it already? Oops!
